# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: machine_failure.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='machine_failure.proto',
  package='machine_failure',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15machine_failure.proto\x12\x0fmachine_failure\"n\n\x10MachineDataPoint\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\x10\n\x08velocity\x18\x04 \x01(\x01\x12\x10\n\x08pressure\x18\x05 \x01(\x01\"D\n\x18MachineFailurePrediction\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x15\n\rfailureChance\x18\x02 \x01(\x01\x62\x06proto3')
)




_MACHINEDATAPOINT = _descriptor.Descriptor(
  name='MachineDataPoint',
  full_name='machine_failure.MachineDataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='machine_failure.MachineDataPoint.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='machine_failure.MachineDataPoint.timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='machine_failure.MachineDataPoint.temperature', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='machine_failure.MachineDataPoint.velocity', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='machine_failure.MachineDataPoint.pressure', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=152,
)


_MACHINEFAILUREPREDICTION = _descriptor.Descriptor(
  name='MachineFailurePrediction',
  full_name='machine_failure.MachineFailurePrediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='machine_failure.MachineFailurePrediction.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failureChance', full_name='machine_failure.MachineFailurePrediction.failureChance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=222,
)

DESCRIPTOR.message_types_by_name['MachineDataPoint'] = _MACHINEDATAPOINT
DESCRIPTOR.message_types_by_name['MachineFailurePrediction'] = _MACHINEFAILUREPREDICTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MachineDataPoint = _reflection.GeneratedProtocolMessageType('MachineDataPoint', (_message.Message,), dict(
  DESCRIPTOR = _MACHINEDATAPOINT,
  __module__ = 'machine_failure_pb2'
  # @@protoc_insertion_point(class_scope:machine_failure.MachineDataPoint)
  ))
_sym_db.RegisterMessage(MachineDataPoint)

MachineFailurePrediction = _reflection.GeneratedProtocolMessageType('MachineFailurePrediction', (_message.Message,), dict(
  DESCRIPTOR = _MACHINEFAILUREPREDICTION,
  __module__ = 'machine_failure_pb2'
  # @@protoc_insertion_point(class_scope:machine_failure.MachineFailurePrediction)
  ))
_sym_db.RegisterMessage(MachineFailurePrediction)


# @@protoc_insertion_point(module_scope)
